include: package:flutter_lints/flutter.yaml

linter:
  rules:
    file_names: true # https://dart-lang.github.io/linter/lints/file_names.html
    avoid_print: true # https://dart-lang.github.io/linter/lints/avoid_print.html
    close_sinks: true # https://dart-lang.github.io/linter/lints/close_sinks.html
    empty_catches: true # https://dart-lang.github.io/linter/lints/empty_catches.html
    null_closures: true # https://dart-lang.github.io/linter/lints/null_closures.html
    package_names: true # https://dart-lang.github.io/linter/lints/package_names.html
    hash_and_equals: true # https://dart-lang.github.io/linter/lints/hash_and_equals.html
    prefer_contains: true # https://dart-lang.github.io/linter/lints/prefer_contains.html
    prefer_is_empty: true # https://dart-lang.github.io/linter/lints/prefer_is_empty.html
    unnecessary_new: true # https://dart-lang.github.io/linter/lints/unnecessary_new.html
    avoid_empty_else: true # https://dart-lang.github.io/linter/lints/avoid_empty_else.html
    avoid_void_async: true # https://dart-lang.github.io/linter/lints/avoid_void_async.html
    camel_case_types: true # https://dart-lang.github.io/linter/lints/camel_case_types.html
    empty_statements: true # https://dart-lang.github.io/linter/lints/empty_statements.html
    throw_in_finally: true # https://dart-lang.github.io/linter/lints/throw_in_finally.html
    unnecessary_this: true # https://dart-lang.github.io/linter/lints/unnecessary_this.html
    unnecessary_late: true # https://dart-lang.github.io/linter/lints/unnecessary_late.html
    recursive_getters: true # https://dart-lang.github.io/linter/lints/recursive_getters.html
    only_throw_errors: true # https://dart-lang.github.io/linter/lints/only_throw_errors.html
    unawaited_futures: true # https://dart-lang.github.io/linter/lints/unawaited_futures.html
    unnecessary_const: true # https://dart-lang.github.io/linter/lints/unnecessary_const.html
    avoid_init_to_null: true # https://dart-lang.github.io/linter/lints/avoid_init_to_null.html
    await_only_futures: true # https://dart-lang.github.io/linter/lints/await_only_futures.html
    eol_at_end_of_file: true # https://dart-lang.github.io/linter/lints/eol_at_end_of_file.html
    directives_ordering: true # https://dart-lang.github.io/linter/lints/directives_ordering.html
    prefer_final_locals: true # https://dart-lang.github.io/linter/lints/prefer_final_locals.html
    prefer_inlined_adds: true # https://dart-lang.github.io/linter/lints/prefer_inlined_adds.html
    prefer_int_literals: true # https://dart-lang.github.io/linter/lints/prefer_int_literals.html
    prefer_is_not_empty: true # https://dart-lang.github.io/linter/lints/prefer_is_not_empty.html
    prefer_void_to_null: true # https://dart-lang.github.io/linter/lints/prefer_void_to_null.html
    secure_pubspec_urls: true # https://dart-lang.github.io/linter/lints/secure_pubspec_urls.html
    use_named_constants: true # https://dart-lang.github.io/linter/lints/use_named_constants.html
    avoid_returning_this: true # https://dart-lang.github.io/linter/lints/avoid_returning_this.html
    cancel_subscriptions: true # https://dart-lang.github.io/linter/lints/cancel_subscriptions.html
    prefer_single_quotes: true # https://dart-lang.github.io/linter/lints/prefer_single_quotes.html
    camel_case_extensions: true # https://dart-lang.github.io/linter/lints/camel_case_extensions.html
    avoid_final_parameters: true # https://dart-lang.github.io/linter/lints/avoid_final_parameters.html
    prefer_is_not_operator: true # https://dart-lang.github.io/linter/lints/prefer_is_not_operator.html
    unnecessary_statements: true # https://dart-lang.github.io/linter/lints/unnecessary_statements.html
    control_flow_in_finally: true # https://dart-lang.github.io/linter/lints/control_flow_in_finally.html
    prefer_relative_imports: true # https://dart-lang.github.io/linter/lints/prefer_relative_imports.html
    empty_constructor_bodies: true # https://dart-lang.github.io/linter/lints/empty_constructor_bodies.html
    no_duplicate_case_values: true # https://dart-lang.github.io/linter/lints/no_duplicate_case_values.html
    no_logic_in_create_state: true # https://dart-lang.github.io/linter/lints/no_logic_in_create_state.html
    prefer_final_in_for_each: true # https://dart-lang.github.io/linter/lints/prefer_final_in_for_each.html
    prefer_if_null_operators: true # https://dart-lang.github.io/linter/lints/prefer_if_null_operators.html
    sized_box_for_whitespace: true # https://dart-lang.github.io/linter/lints/sized_box_for_whitespace.html
    constant_identifier_names: true # https://dart-lang.github.io/linter/lints/constant_identifier_names.html
    omit_local_variable_types: true # https://dart-lang.github.io/linter/lints/omit_local_variable_types.html
    avoid_relative_lib_imports: true # https://dart-lang.github.io/linter/lints/avoid_relative_lib_imports.html
    list_remove_unrelated_type: true # https://dart-lang.github.io/linter/lints/list_remove_unrelated_type.html
    always_declare_return_types: true # https://dart-lang.github.io/linter/lints/always_declare_return_types.html
    avoid_escaping_inner_quotes: true # https://dart-lang.github.io/linter/lints/avoid_escaping_inner_quotes.html
    prefer_initializing_formals: true # https://dart-lang.github.io/linter/lints/prefer_initializing_formals.html
    avoid_unnecessary_containers: true # https://dart-lang.github.io/linter/lints/avoid_unnecessary_containers.html
    avoid_returning_null_for_void: true # https://dart-lang.github.io/linter/lints/avoid_returning_null_for_void.html
    avoid_return_types_on_setters: true # https://dart-lang.github.io/linter/lints/avoid_return_types_on_setters.html
    depend_on_referenced_packages: true # https://dart-lang.github.io/linter/lints/depend_on_referenced_packages.html
    avoid_types_as_parameter_names: true # https://dart-lang.github.io/linter/lints/avoid_types_as_parameter_names.html
    avoid_web_libraries_in_flutter: true # https://dart-lang.github.io/linter/lints/avoid_web_libraries_in_flutter.html
    prefer_null_aware_method_calls: true # https://dart-lang.github.io/linter/lints/prefer_null_aware_method_calls.html
    unnecessary_to_list_in_spreads: true # https://dart-lang.github.io/linter/lints/unnecessary_to_list_in_spreads.html
    use_key_in_widget_constructors: true # https://dart-lang.github.io/linter/lints/use_key_in_widget_constructors.html
    avoid_redundant_argument_values: true # https://dart-lang.github.io/linter/lints/avoid_redundant_argument_values.html
    avoid_catches_without_on_clauses: true # https://dart-lang.github.io/linter/lints/avoid_catches_without_on_clauses.html
    avoid_renaming_method_parameters: true # https://dart-lang.github.io/linter/lints/avoid_renaming_method_parameters.html
    iterable_contains_unrelated_type: true # https://dart-lang.github.io/linter/lints/iterable_contains_unrelated_type.html
    literal_only_boolean_expressions: true # https://dart-lang.github.io/linter/lints/literal_only_boolean_expressions.html
    avoid_types_on_closure_parameters: true # https://dart-lang.github.io/linter/lints/avoid_types_on_closure_parameters.html
    unnecessary_string_interpolations: true # https://dart-lang.github.io/linter/lints/unnecessary_string_interpolations.html
    avoid_positional_boolean_parameters: true # https://dart-lang.github.io/linter/lints/avoid_positional_boolean_parameters.html
    unnecessary_brace_in_string_interps: true # https://dart-lang.github.io/linter/lints/unnecessary_brace_in_string_interps.html
    avoid_multiple_declarations_per_line: true # https://dart-lang.github.io/linter/lints/avoid_multiple_declarations_per_line.html
    unnecessary_null_in_if_null_operators: true # https://dart-lang.github.io/linter/lints/unnecessary_null_in_if_null_operators.html
    use_if_null_to_convert_nulls_to_bools: true # https://dart-lang.github.io/linter/lints/use_if_null_to_convert_nulls_to_bools.html
    null_check_on_nullable_type_parameter: true # https://dart-lang.github.io/linter/lints/null_check_on_nullable_type_parameter.html
    avoid_null_checks_in_equality_operators: true # https://dart-lang.github.io/linter/lints/avoid_null_checks_in_equality_operators.html
    curly_braces_in_flow_control_structures: true # https://dart-lang.github.io/linter/lints/curly_braces_in_flow_control_structures.html
    prefer_for_elements_to_map_fromIterable: true # https://dart-lang.github.io/linter/lints/prefer_for_elements_to_map_fromIterable.html
    prefer_interpolation_to_compose_strings: true # https://dart-lang.github.io/linter/lints/prefer_interpolation_to_compose_strings.html
    always_put_required_named_parameters_first: true # https://dart-lang.github.io/linter/lints/always_put_required_named_parameters_first.html
    no_leading_underscores_for_local_identifiers: true # https://dart-lang.github.io/linter/lints/no_leading_underscores_for_local_identifiers.html
    avoid_single_cascade_in_expression_statements: true # https://dart-lang.github.io/linter/lints/avoid_single_cascade_in_expression_statements.html
    avoid_bool_literals_in_conditional_expressions: true # https://dart-lang.github.io/linter/lints/avoid_bool_literals_in_conditional_expressions.html

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
